FORMAT: 1A
HOST: http://server.wwsu1069.org

# wwsu

The WWSU Radio Sails.js API application enables external / remote control of core WWSU functionality. Applications can be developed utilizing this API.

## User [/user]

### /user/auth Authorization [POST /user/auth]

A lot of API endpoints require a valid authorization in the form of a header. 
The key is "authorization", and the value is "Bearer (token)". 
Use the /user/auth endpoint to authenticate and get a token.
User accounts are issued by WWSU. They are not available on request.

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + email: null@example.com (string, required)
        + password: password (string, required)

+ Response 200 (application/json)

        {
             "user": {
                 "email": "null@example.com",
                 "id": 0,
                  "createdAt": "2018-02-15T18:00:01.000Z",
                  "updatedAt": "2018-02-15T18:00:01.000Z"
              },
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTI1MTI5NTY3LCJleHAiOjE1MjUxMzA0Njd9.1QOmO3EzvkvMBSf5WohMFnCSYzCXxLBFAp-JUrUUGq0"
        }
    
+ Response 401 (application/json)

        {
            "err": "Email and password required."
        }
        
+ Response 401 (application/json)

        {
            "err": "Invalid Token!"
        }
        
## Directors [/directors]

Directors endpoints regard the directors of WWSU Radio.

### /directors/get [GET /directors/get]

Get one specific director of WWSU.

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + username: login (string, required)

+ Response 200 (application/json)

        [
            "George Carlin": { // Full name of the director
                "position": "General Manager", // Director's occupation with WWSU
                "present": false, // False = clocked out, True = clocked in
                "since": "2018-04-30T19:51:16.000Z" // Time at which present last changed
            }
        ]

+ Response 404
+ Response 500

### /directors/getall [GET /directors/getall]

Get all directors of WWSU as an array. If the request is a web socket, the request will be subscribed to the directors event to receive changes to any of the directors. Changes to directors will be passed in an array as a directors event; only updated/new directors will be included in that array. Deleted directors will be passed as a directors-remove event, where the data is a string containing the name of the director to be deleted by the client.

+ Response 200 (application/json)

        [
            "George Carlin": { // Full name of the director
                "position": "General Manager", // Director's occupation with WWSU
                "present": false, // False = clocked out, True = clocked in
                "since": "2018-04-30T19:51:16.000Z" // Time at which present last changed
            },
            ...
        ]
+ Response 500
        
## Discipline [/discipline]

Discipline endpoints manage moderation of website and mobile app users.

### /discipline/ban-show [POST /discipline/ban-show]

Bans the specified user until the currently live DJ/broadcast ends. Also mass deletes all website messages sent by the specified user.
**Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + host: AAAAAA (string, required)
        
+ Response 200
+ Response 500

### /discipline/ban-day [POST /discipline/ban-day]

Bans the specified user for 24 hours. Also mass deletes all website messages sent by the specified user.
**Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + host: AAAAA (string, required)
        
+ Response 200
+ Response 500

### /discipline/ban-indefinite [POST /discipline/ban-indefinite]

Bans the specified user indefinitely. Also mass deletes all website messages sent by the specified user.
**Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + host: AAAAA (string, required)
        
+ Response 200
+ Response 500
    
## Display [/display]

These endpoints deal with the public WWSU display signs

### /display/public [GET /display/public]

Get the public display sign as HTML webpage; to be run in full screen on the display monitor. This is for the general public.

+ Response 200 (text/html)
+ Response 500

### /display/internal [GET /display/internal]

Get the internal display sign as HTML webpage; to be run in full screen on the display monitor. This is for directors and members of the WWSU organization

+ Response 200 (text/html)
+ Response 500

### /display/refresh [GET /display/refresh]

Send a refresh signal to all connected display signs via websockets. **Requires authorization**.

+ Response 200 (application/json)
+ Response 500

## Eas [/eas]

Eas endpoints deal with the internal WWSU emergency alert system. These endpoints do NOT have anything to do with the SAGE Digital ENDEC; this is internal only.

### /eas/get [GET /eas/get]

Get an array of currently active alerts. If the request is a socket, will also be subscribed to EAS events. New/updated alerts will be passed as an array to the EAS event. Alerts to be deleted will be passed as a number to the EAS-remove event, where the number is the ID of the alert to be deleted.

+ Response 200 (application/json)

        [
            {
                "createdAt": "2018-05-07T02:00:12.350Z",
                "updatedAt": "2018-05-07T02:00:12.367Z",
                "ID": 12,
                "source": "WWSU",
                "reference": "1525658412343",
                "alert": "Test",
                "information": "This is a test of the WWSU Emergency Alert System. This is only a test. The WWSU Emergency Alert System is designed to provide the public with timely emergency information, as well as weather alerts for Clark, Greene, and Montgomery counties of Ohio. Had this been an actual emergency, you would have received information and instructions regarding the emergency. This concludes the test of the WWSU Emergency Alert System.",
                "severity": "Extreme",
                "color": "#FFFFFF",
                "counties": "Clark, Greene, Montgomery",
                "starts": "2018-05-07T02:00:12.343Z",
                "expires": "2018-05-07T02:03:12.343Z",
                "push": false
            }
            ...
        ]
        
+ Response 500

### /eas/send [POST /eas/send]

Issue a new alert through the internal emergency alert system, originating from WWSU. **Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + counties: Clark, Greene, Montgomery (string, required)
        + alert: Bomb Threat (string, required)
        + severity: Extreme (string, required)
        + starts: 2018-05-06T21:43:07+00:00 (string)
        + expires: 2018-05-06T21:58:07+00:00 (string)
        + color: #000000 (string, required)
        + Information: A bomb threat has been detected. Please evacuate into bomb shelters immediately. The entire campus is on lockdown. (string, required)
        
+ Response 200
+ Response 500

### /eas/test [POST /eas/test]

Send out a test through the internal emergency alert system. **Requires authorization**

+ Response 200
+ Response 500

## Events [/events]

Events endpoints deal with the Google Calendar events of WWSU Radio (such as show and genre schedules / programming).

### /events/get [GET /events/get]

Get an array of events for the next 7 days, in no particular order (client will need to do their own sorting). If the request is a socket, will also be subscribed to receive changes to events. New/updated events will be sent as an array to the events event. Deleted events will be sent as a number (the ID of the event that was deleted) to the events-remove event.

+ Response 200 (application/json)

        [
            {
                "createdAt": "2018-05-15T22:31:34.381Z",
                "updatedAt": "2018-05-15T22:31:34.381Z",
                "ID": 1,
                "unique": "578vfod7icjde4ikdbmtii9ren_20180516T080000Z", // Unique event ID as provided by Google Calendar
                "title": "Genre: New Rock", // Title of the event
                "description": "", // Description of the event, if provided (HTML is stripped from the Google Calendar API field)
                "allDay": false, // True if this is an all day event
                "start": "2018-05-16T04:00:00-04:00", // ISO string of the event start time
                "end": "2018-05-16T08:00:00-04:00", // ISO string of the event end time
                "color": "#5484ed", // Hexadecimal color representing this event
                "push": false // Used internally to determine which events need to be sent through web sockets. No beneficial client use.
            },
            ...
        ]
        
+ Response 500
 upda
## Messages [/messages]

Messages endpoints regard the internal messaging system with WWSU Radio.

### /messages/remove [POST /messages/remove]

Delete a message. Sends a websocket message to all connected clients to remove the message. **Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + ID: 0 (number, required)
        
+ Response 200
+ Response 500

### /messages/find-recipients [GET /messages/find-recipients]

Retrieve a list (in the form of an Object) of recipients that can be sent a message. If request is a websocket, will be subscribed to receive changes to the recipients or their statuses. New/updated recipients will be passed as an Object to the message-user event. For example, a change to a user in the system group will be received as {system: {emergency: {label: 'Technical Issues', status: 0}}. Use lodash merging to merge this object with the complete users object stored in client memory. Also, deleted users will be passed as a string to the message-user-remove event, where the string is the key of the user to remove. Using the example with updating, if the emergency user is removed, message-user-remove will pass 'emergency'.
        
+ Response 200 (application/json)

        {
            "system": {
                "emergency": {
                    "label": "Technical Issues",
                    "status": 0 // 0 = No issues, 1 = issue reported
                },
                "trackrequests": {
                    "label": "Track Requests",
                    "status": 0 // 0 = no requests, 4 = request pending
                }
            },
            "website": {
                "website": {
                    "label": "Web Public",
                    "status": 5 // 5 = online, 0 = offline/disabled
                },
                ...
            },
            "computers": {
                "hostname": {
                    "label": "OnAir Computer",
                    "status": 2 // 2 = online, 0 = offline
                },
                ...
            },
            "display": {
                "public": {
                    "label": "Display public",
                    "status": 2 // 2 = online, 0 = offline
                },
                ...
            }
        }
+ Response 500

### /messages/read [GET /messages/read]

Retrieve a list of messages sent within the last hour. Used by internal WWSU applications. If request is websocket, will be subscribed to receive new messages sent. New/updated messages will be passed as an array to the message-message event. Deleted messages will be passed as a number (the ID of the message deleted) to the message-remove event. **Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + host: OnAirPC (string, required)
        
+ Response 200 (application/json)

        [
            {
                "createdAt": "2018-05-03T23:18:41.089Z",
                "updatedAt": "2018-05-03T23:18:41.089Z",
                "ID": 1,
                "status": "active",
                "from": "Me", // Host
                "from_friendly": "Me",
                "from_IP": "Not Specified",
                "to": "You", // Host
                "to_friendly": "You too",
                "message": "hi"
            },
            ...
        ]

+ Response 500

### /messages/read-emergencies [GET /messages/read-emergencies]

Retrieve a list of active technical issues reported. Used by internal WWSU applications. If request is websocket, will be subscribed to receive new reported technical issues. Emergency messages will be passed as an array to the message-emergency event. Deleted emergency messages will be passed as a number (ID of the message to be deleted) to the message-remove event. **Requires authorization**
        
+ Response 200 (application/json)

        [
            {
                "createdAt": "2018-05-03T23:18:41.089Z",
                "updatedAt": "2018-05-03T23:18:41.089Z",
                "ID": 1,
                "status": "active",
                "from": "Me", // Host
                "from_friendly": "Me",
                "from_IP": "Not Specified",
                "to": "emergency", 
                "to_friendly": "emergency",
                "message": "RadioDJ crashed"
            },
            ...
        ]

+ Response 500

### /messages/read-web [GET /messages/read-web]

Retrieve a list of messages sent within the last hour applicable to web and mobile users. If request is websocket, will be subscribed to receive new messages. New messages will be passed as an array to the message-message event. Deleted messages will be passed as a number (ID of the message deleted) to the message-remove event. Client may receive message-remove event calls for messages not pertaining to them / not received by them, so be sure to have a check for that.

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + nickname: George Carlin (string)
        
+ Response 200 (application/json)

        [
            {
                "createdAt": "2018-05-03T23:18:41.089Z",
                "updatedAt": "2018-05-03T23:18:41.089Z",
                "ID": 1,
                "status": "active",
                "from": "Me", // Messages from other web/mobile clients will begin with website-
                "from_friendly": "Me",
                "to": "website", // website = all web/mobile clients, website-hostid = specific web/mobile client, DJ = Public message to the DJ, DJ-private = Private message to the DJ
                "to_friendly": "You too",
                "message": "hi"
            },
            ...
        ]

+ Response 500

### /messages/send [POST /messages/send]

Sends a message. This is used by internal WWSU clients. **Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + from: AAAAAA (string, required)
        + to: AAAAAA (string, required)
        + to_friendly: Engineering Computer (string, required)
        + message: Fix the Automation System (string, required)
        
+ Response 200
+ Response 500

### /messages/send-web [POST /messages/send-web]

Sends a message. This is used by public web and mobile clients.

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + nickname: George Carlin (string)
        + private: false (boolean, required) // true = only the DJ can see the message; other public clients cannot see it
        + message: Fix the Automation System (string, required)
        
+ Response 200
+ Response 500

## Meta [/meta]

Meta endpoints regard metadata, or what is currently playing / on the air.

### /meta/get [GET /meta/get]

Get the current meta. If request is a socket, will also be subscribed to the meta event, which will receive meta changes.

+ Response 200 (application/json)

        {
            state: 'unknown', // State of the WWSU system
            dj: '', // If someone is on the air, name of the host
            track: '', // Currently playing track either in automation or manually logged
            trackstamp: null, // Use moment.toISOString() when changing in changeMeta! If you directly store a moment instance here, database updating will fail
            topic: '', // If the DJ specified a show topic, this is the topic.
            stream: '', // Meta for the internet radio stream
            radiodj: '', // REST IP of the RadioDJ instance currently in control
            djcontrols: '', // Hostname of the computer in which has activated the most recent live/sports/remote broadcast via DJ Controls
            line1: '', // First line of meta for display signs
            line2: '', // Second line of meta for display signs
            percent: 0, // Integer or float between 0 and 100 indicating how far in the current track in automation we are, for display signs
            time: '', // Human readable date and time for display signs
            listeners: 0, // Number of current online listeners
            listenerpeak: 0, // Number of peak online listeners
            queueLength: 0, // Amount of audio queued in radioDJ in seconds (can be a float)
            breakneeded: false, // If the current DJ needs to take the FCC required top of the hour break, this will be true
            status: 4, // Overall system status: 1 = major outage, 2 = partial outage, 3 = minor issue, 4 = rebooting, 5 = operational
            webchat: true, // Set to false to restrict the ability to send chat messages through the website
            playlist: null, // Name of the playlist we are currently airing
            playlist_position: -1, // Current position within the playlist
            playlist_played: null // Use moment.toISOString() when changing in changeMeta! If you directly store a moment instance here, database updating will fail
        }
        
## Requests [/requests]

Requests endpoints deal with the WWSU track request system.

### /requests/get [GET /requests/get]

Get an array of requested tracks. If the request is a socket, will also be subscribed to receive new/played requests. When a new request is placed, it will be passed as an array to the request event. When a request is played, the ID of the request will be passed to the request-remove event. **Requires authorization**
**NOTE:** This may return requests that have already been queued; requests do not get marked as removed until they have actually played. Any requests a client attempts to queue via. requests/queue that are already in the queue will be returned with an error that it is already in the queue.

+ Response 200 (application/json)

        [
            // Response format TBD
        ]
+ Response 500

### /requests/place [POST /requests/place]

Place a track request in the system.

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + ID: 1 (number, required)
        + name: George Carlin (string)
        + message: This track is the best Classic Rock you could get for radio. (string)
        
+ Response 200

        {
            requested: true, // True if the track request was accepted, false if it was rejected (such as it is already in the queue, or it fails rotation rules)
            HTML: `<div class="alert alert-success" role="alert">
                                            Request placed! In automation, requests are queued every :20, :40, and :00 past the hour. If a show is live, it is up to the host's discretion of when/if to play requests.
                                            </div>` // an HTML response suitable for the track request webpage.
        }
        
+ Response 500

### /requests/queue [POST /requests/queue]

Immediately queue or play a request. If in automation, will queue it to the top. If live / sports / remote / sportsremote, will queue and immediately begin playing it. **Requires authorization**

+ Request (application/x-www-form-urlencoded)

    + Attributes

        + ID: 1 (number, required)
        
+ Response 200

        true // Returns true if the requests was queued, false if the request was not queued (usually the cause of already being in the queue or have already been played)
        
+ Response 500
        
## Status [/status]

Status endpoints refer to the status of WWSU subsystems.

### /status/get [GET /status/get]

Get an array of statuss of WWSU sub-systems. If the request is a socket, the request will be subscribed to the status event to receive changes to statuses. Changes to status will be passed as an array as a status event; only changed statuses will be included in this array. There are no delete events for statuses.

+ Response 200 (application/json)

        [
            "database": {
                "label": "Database", // Friendly name
                "status": 5, // 1 = critical issue, 2 = major issue, 3 = minor issue, 4 = offline, 5 = good
                "time": "2018-04-30T23:21:06.204Z" // Time at which the subsystem last had a good (5) status
            },
            ...
        ]
+ Response 500